run:
  timeout: 5m
linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - ineffassign
    - staticcheck
    - errcheck
    - unused
    - goimports
    - misspell
    - unconvert
    - unparam
